<?php
/**
 * @var stdClass $PageData данные для страницы.
 */
?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type="text/javascript" src="<?= JS_CORE_PATH ?>jquery-latest.js"></script>
        <script type="text/javascript" src="<?= JS_CORE_PATH ?>main.js"></script>
        <?php
            if (isset($PageData->header)) {
                require_once ($PageData->header);
            }
        ?>
    </head>
    <body>
        <?php require_once ($PageData->content); ?>
        <script type="text/javascript">
            Core.Data._data = jQuery.parseJSON('<?= $PageData->jsData; ?>');
        </script>
    </body>
</html>
